import type { Metadata } from "next"

export const metadata: Metadata = {
    title: 'Authentication Screen',
    description: 'Generated by clerk',
}

export default function AuthLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <div className="flex justify-center items-center h-full fixed inset-0 bg-black/10 backdrop-blur-sm z-[1000]">
            {children}
        </div>
    )
}